[book]
authors = ["veltzer"]
language = "en"
src = "src"
title = "RSMultiGit - Rust Multi-Git"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rmg"
edit-url-template = "https://github.com/veltzer/rmg/edit/master/docs/{path}"
